import fs from 'node:fs'
import path from 'node:path'
import type { HeadConfig, PageData, TransformContext } from 'vitepress'
import { faq, Product, products, SITE_URL } from './data/products'

const SITE_NAME = 'Pavel on AsyncAPI'
const DEFAULT_IMAGE = '/asyncapi.png'
const DOCS_ROOT = path.resolve(__dirname, '..')

const PERSON_ID = `${SITE_URL}/#person`
const WEBSITE_ID = `${SITE_URL}/#website`

// Tags generated by `transformHead`; any copy in frontmatter `head` is dropped to avoid duplicates and wrong values
const isGeneratedTag = ([tag, attrs]: HeadConfig) =>
  (tag === 'link' && attrs?.rel === 'canonical') ||
  (tag === 'meta' && /^(og:|twitter:)/.test(String(attrs?.property ?? attrs?.name ?? '')))

const absolute = (url: string) => (/^https?:\/\//.test(url) ? url : `${SITE_URL}${url.startsWith('/') ? '' : '/'}${url}`)

/** Public URL of a page; `index.md` maps to its directory (matches the generated sitemap) */
export const pageUrl = (relativePath: string) =>
  `${SITE_URL}/${relativePath.replace(/(^|\/)index\.md$/, '$1').replace(/\.md$/, '.html')}`

/**
 * Pull the per-page image out of frontmatter and drop hand-written canonical/og/twitter tags.
 * Runs before rendering; `transformHead` regenerates all of them consistently.
 */
export function normalizePageData(pageData: PageData) {
  const head = (pageData.frontmatter.head ?? []) as HeadConfig[]
  const image = head.find(([tag, attrs]) => tag === 'meta' && (attrs?.name ?? attrs?.property) === 'og:image')
  if (image) pageData.frontmatter.ogImage = String(image[1].content)
  pageData.frontmatter.head = head.filter((h) => !isGeneratedTag(h))
}

const person = {
  '@type': 'Person',
  '@id': PERSON_ID,
  name: 'Pavel Bodiachevskii',
  url: 'https://pavelon.dev',
  jobTitle: 'AsyncAPI Technical Steering Committee member and maintainer',
  memberOf: {
    '@type': 'OrganizationRole',
    roleName: 'Technical Steering Committee member',
    memberOf: { '@type': 'Organization', name: 'AsyncAPI Initiative', url: 'https://www.asyncapi.com' },
  },
  knowsAbout: ['AsyncAPI', 'Event-driven architecture', 'Apache Kafka', 'Spring Messaging', 'JetBrains IDE plugins'],
  sameAs: ['https://github.com/Pakisan', 'https://pavelon.dev', 'https://plugins.jetbrains.com/plugin/15673-asyncapi'],
}

const website = {
  '@type': 'WebSite',
  '@id': WEBSITE_ID,
  url: SITE_URL,
  name: SITE_NAME,
  inLanguage: 'en',
  publisher: { '@id': PERSON_ID },
}

function softwareApplication(p: Product) {
  const url = `${SITE_URL}${p.page}`
  const node: Record<string, unknown> = {
    '@type': 'SoftwareApplication',
    '@id': `${url}#software`,
    name: p.name,
    description: p.summary,
    url,
    applicationCategory: p.applicationCategory,
    operatingSystem: p.operatingSystem,
    featureList: p.features,
    audience: { '@type': 'Audience', audienceType: p.audience },
    author: { '@id': PERSON_ID },
    creator: { '@id': PERSON_ID },
  }
  if (p.softwareVersion) node.softwareVersion = p.softwareVersion
  if (p.repoUrl) node.codeRepository = p.repoUrl
  if (p.status === 'available') {
    node.offers = { '@type': 'Offer', price: '0', priceCurrency: 'USD' }
    if (p.id === 'jasyncapi') node.license = 'https://www.apache.org/licenses/LICENSE-2.0'
  } else if (p.status === 'freemium') {
    node.offers = {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
      description: 'Free core features; additional features are available in the paid tier',
    }
  }
  if (p.installUrl) node.downloadUrl = p.installUrl
  return node
}

const SEGMENT_LABELS: Record<string, string> = {
  bindings: 'Bindings',
  schemas: 'Schemas',
  'jetbrains-plugin': 'JetBrains Plugin',
}

function breadcrumbs(relativePath: string, title: string) {
  const segments = relativePath.replace(/\.md$/, '').split('/')
  const isIndex = segments[segments.length - 1] === 'index'
  if (isIndex) segments.pop()
  if (segments.length === 0) return null

  const items: { name: string; url: string }[] = [{ name: 'Home', url: `${SITE_URL}/` }]
  // Only link ancestors that are real pages (e.g. /bindings/mqtt/ yes, /bindings/mqtt/0.2.0/ no)
  segments.slice(0, -1).forEach((seg, i) => {
    const dir = segments.slice(0, i + 1).join('/')
    if (fs.existsSync(path.join(DOCS_ROOT, dir, 'index.md'))) {
      items.push({ name: SEGMENT_LABELS[seg] ?? seg, url: `${SITE_URL}/${dir}/` })
    }
  })
  items.push({ name: title, url: pageUrl(relativePath) })

  return {
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, i) => ({ '@type': 'ListItem', position: i + 1, name: item.name, item: item.url })),
  }
}

function pageGraph(ctx: TransformContext, title: string, description: string, url: string, image: string) {
  const { pageData } = ctx
  const rel = pageData.relativePath
  const graph: Record<string, unknown>[] = [person, website]
  const modified = pageData.lastUpdated ? new Date(pageData.lastUpdated).toISOString() : undefined

  if (rel === 'index.md') {
    graph.push({
      '@type': 'CollectionPage',
      '@id': `${url}#webpage`,
      url,
      name: title,
      description,
      isPartOf: { '@id': WEBSITE_ID },
      about: { '@id': PERSON_ID },
      primaryImageOfPage: image,
    })
    const software = products.filter((p) => p.group !== 'Reference')
    graph.push({
      '@type': 'ItemList',
      name: 'AsyncAPI tools by Pavel Bodiachevskii',
      itemListElement: software.map((p, i) => ({ '@type': 'ListItem', position: i + 1, item: softwareApplication(p) })),
    })
    graph.push({
      '@type': 'FAQPage',
      mainEntity: faq.map((f) => ({
        '@type': 'Question',
        name: f.q,
        acceptedAnswer: { '@type': 'Answer', text: f.a },
      })),
    })
    return graph
  }

  const product = products.find((p) => p.page === `/${rel.replace(/(^|\/)index\.md$/, '$1').replace(/\.md$/, '.html')}`)
  if (product && product.group !== 'Reference') {
    graph.push({ ...softwareApplication(product), mainEntityOfPage: url, image })
  } else {
    graph.push({
      '@type': 'TechArticle',
      '@id': `${url}#article`,
      headline: title,
      description,
      url,
      image,
      inLanguage: 'en',
      author: { '@id': PERSON_ID },
      publisher: { '@id': PERSON_ID },
      isPartOf: { '@id': WEBSITE_ID },
      mainEntityOfPage: url,
      ...(modified && { dateModified: modified }),
    })
  }

  const crumbs = breadcrumbs(rel, title)
  if (crumbs) graph.push(crumbs)
  return graph
}

export function buildHead(ctx: TransformContext): HeadConfig[] {
  const { pageData, siteData } = ctx
  const fm = pageData.frontmatter
  const title = String(fm.title || pageData.title || siteData.title)
  const description = String(fm.description || pageData.description || siteData.description)
  const url = pageUrl(pageData.relativePath)
  const image = absolute(String(fm.ogImage || fm.image || DEFAULT_IMAGE))
  const isHome = pageData.relativePath === 'index.md'

  const head: HeadConfig[] = [
    ['link', { rel: 'canonical', href: url }],
    ['meta', { property: 'og:site_name', content: SITE_NAME }],
    ['meta', { property: 'og:locale', content: 'en_US' }],
    ['meta', { property: 'og:type', content: isHome ? 'website' : 'article' }],
    ['meta', { property: 'og:title', content: title }],
    ['meta', { property: 'og:description', content: description }],
    ['meta', { property: 'og:url', content: url }],
    ['meta', { property: 'og:image', content: image }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['meta', { name: 'twitter:title', content: title }],
    ['meta', { name: 'twitter:description', content: description }],
    ['meta', { name: 'twitter:image', content: image }],
  ]
  if (!isHome && pageData.lastUpdated) {
    head.push(['meta', { property: 'article:modified_time', content: new Date(pageData.lastUpdated).toISOString() }])
  }
  head.push(['script', { type: 'application/ld+json' }, JSON.stringify({ '@context': 'https://schema.org', '@graph': pageGraph(ctx, title, description, url, image) })])
  return head
}
